### ISSUE TITLE
The output tiff file is corrupted

### ISSUE THREAD

**Issue by guosiliang** [biomicroscopy/DPR-Project#1]
Hello, your project is particularly inspiring to me, but when I try to run the demo file, the tiff file output can not be displayed normally, how to solve it?
My environment is matlab2017b, did not call mex file, but called DPR_UpdateSingle.m source code.
![image](https://github.com/biomicroscopy/DPR-Project/assets/49401788/13b49488-ea56-4024-99df-3d40103c0d50)
the output tiff file is as follows:
![image](https://github.com/biomicroscopy/DPR-Project/assets/49401788/dea0e1f6-03e4-4326-bfbd-2f35f97b24e0)
![image](https://github.com/biomicroscopy/DPR-Project/assets/49401788/52c27b91-2288-4e85-86a7-7c61df1bfc58)

**Comment by bbbying12** [comment]
Hi,

Could you open and display the output tiff image in Matlab?

**Comment by AymericFerreira** [comment]
As I wrote to https://github.com/biomicroscopy/DPR-Project/issues/2
You will probably need a image viewer that supports bigtiff. If your viewer is old, you could need to update it or you can try with FIJI, it is working for me : https://imagej.net/software/fiji/

**Comment by bbbying12** [comment]
Hello @guosiliang , I’ve updated the MATLAB code, added a new Python implementation, and enhanced the README with additional instructions. The issue should be resolved now. Please check the updated version, and if the problem persists, don’t hesitate to email me or open a new issue. Thank you!
