### ISSUE TITLE
The  input and out tif files can not be  opened

### ISSUE THREAD

**Issue by blingsr** [biomicroscopy/DPR-Project#2]
The  input and out tif files can not be  opened.

**Comment by AymericFerreira** [comment]
Images seems to be bigtiff, I had with issue with old version of FIJI but managed to open it with version 2.14 of FIJI (based on ImageJ 1.54)

**Comment by bbbying12** [comment]
@blingsr @AymericFerreira - Thank you for your involvement in the project. I've updated the MATLAB code to include displays of both the initial and resulting images. Additionally, I’ve added a Python implementation of the algorithm. Please feel free to review these updates if you’re interested.
